# For full config options, check the docs:    docs.serverless.com

service: lambdaNodejs
provider:
  name: aws
  runtime: nodejs8.10
stage: dev
region: us-west-1
functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: /
         method: get
  getProductData:
    handler: handler.getProductData
    events:
      - http:
          path: products
          method: get
